Issue#38 - Flip Order of Gamma and Beta
jpmorganchase/QOKit pull request #48
Opened 2024-03-28 15:08 UTC by rajgane07

@rsln-s @ZichangHe 

Made changes and tested. Please review and merge

2024-03-28 21:28 UTC, rsln-s commented
@ZichangHe would you mind reviewing? Thank you!

2024-03-29 04:32 UTC, ZichangHe commented
I fixed some inconsistent issues in the example notebooks. Otherwise, looks good to me! 

A quick question, how to restore outputs in jupyter notebooks?

2024-03-29 13:44 UTC, rsln-s commented
> A quick question, how to restore outputs in jupyter notebooks?

On OmniQ, you can delete hooks: 
```
cd QOKit
rm .git/hooks/*
```

2024-03-29 13:49 UTC, rsln-s requested changes
Thank you @rajgane07 and @ZichangHe! Special thanks to @ZichangHe for fixing the notebooks – it is important we keep them up-to-date.

@rajgane07, may I ask you to fix the comments and rerun the notebooks so that the output is displayed on Github?

2024-03-29 13:49 UTC, rsln-s commented on examples/QAOA_LABS_optimization.ipynb
>      "import qokit\n",
Unused import, please remove!

2024-03-29 13:49 UTC, rsln-s commented on examples/QAOA_LABS_optimization.ipynb
> +    "import qokit.fur \n",
Unused import, please remove!

2024-03-29 13:49 UTC, rsln-s commented on examples/advanced/compare_maxcut_parameters.ipynb
> +    "N = 10\n",
Can we put 20 back in? Why switch to 10? 20 should be fast enough with `c` simulator even on CPU.

2024-03-29 18:23 UTC, ZichangHe commented
Fixed the two minor change.

2024-03-29 18:24 UTC, ZichangHe approved these changes

2024-04-03 20:16 UTC, rsln-s approved these changes
LGTM

2024-04-03 20:16 UTC, merged